const $=id=>document.getElementById(id);let active=false,watchId=null,last=null,totalKm=0,startTime=null,timer=null;let data=JSON.parse(localStorage.getItem('driverpro')||'{}');
function money(v){return (Number(v)||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'})}function render(){const income=Number(data.income)||0,expense=(Number(data.fuel)||0)+(Number(data.other)||0),profit=income-expense; $('km').textContent=totalKm.toFixed(2).replace('.',',')+' km';$('income').textContent=money(income);$('expense').textContent=money(expense);$('profit').textContent=money(profit);$('profitKm').textContent=money(totalKm?profit/totalKm:0);const goal=Number(data.goal)||400;$('goalBar').style.width=Math.min(100,income/goal*100)+'%';$('goalPct').textContent=Math.round(income/goal*100)+'%';const eff=Math.max(0,Math.min(100,profit/(income||1)*100));$('effBar').style.width=eff+'%';$('effPct').textContent=Math.round(eff)+'%';}
function save(){data={income:$('incomeInput').value,fuel:$('fuelInput').value,other:$('otherInput').value,goal:$('goalInput').value};localStorage.setItem('driverpro',JSON.stringify(data));render()}
function load(){for(const k of ['income','fuel','other','goal'])if(data[k]!=null)$(`${k}Input`).value=data[k];render()}
function distance(a,b){const R=6371,rad=x=>x*Math.PI/180,dLat=rad(b.lat-a.lat),dLon=rad(b.lon-a.lon),x=Math.sin(dLat/2)**2+Math.cos(rad(a.lat))*Math.cos(rad(b.lat))*Math.sin(dLon/2)**2;return R*2*Math.atan2(Math.sqrt(x),Math.sqrt(1-x))}
function start(){if(!navigator.geolocation){alert('Este aparelho/navegador não oferece GPS.');return}active=true;startTime=Date.now();last=null;totalKm=0;$('toggle').textContent='■ Encerrar turno';$('toggle').classList.add('stop');$('status').textContent='● Turno em andamento';$('status').className='pill online';$('gpsText').textContent='GPS ativo';watchId=navigator.geolocation.watchPosition(pos=>{const p={lat:pos.coords.latitude,lon:pos.coords.longitude};if(last){const d=distance(last,p);if(d<0.2)totalKm+=d}last=p;render()},err=>{$('gpsText').textContent='GPS: '+err.message},{enableHighAccuracy:true,maximumAge:5000,timeout:10000});timer=setInterval(()=>{$('timer').textContent=fmt(Date.now()-startTime)},1000)}
function stop(){active=false;if(watchId!==null)navigator.geolocation.clearWatch(watchId);clearInterval(timer);watchId=null;$('toggle').textContent='▶ Iniciar turno';$('toggle').classList.remove('stop');$('status').textContent='● Turno encerrado';$('status').className='pill offline';$('gpsText').textContent='GPS encerrado';}
function fmt(ms){let s=Math.floor(ms/1000),h=Math.floor(s/3600);s%=3600;let m=Math.floor(s/60);s%=60;return [h,m,s].map((x,i)=>i?String(x).padStart(2,'0'):String(x).padStart(2,'0')).join(':')}
$('toggle').onclick=()=>active?stop():start;$('save').onclick=save;$('clear').onclick=()=>{data={};localStorage.removeItem('driverpro');$('incomeInput').value=$('fuelInput').value=$('otherInput').value='';$('goalInput').value=400;render()};load();
